name: "All Green"

brand: "#98FB98"
muted: "#98FB98"

ready: white
listening: white
thinking: white
speaking: white
error: white

user: yellow
assistant: red
instruction: bright_green

assistant_border: bright_green
status_border: bright_green
conversation_border: bright_green
verbose_border: bright_green
system_border: bright_green

normal: bright_green
rule: bright_green
table_header: bright_green
table_text: bright_green
ok: bright_green
total: bold bright_green
conversation_label: bright_green
battery: "#98FB98"
